config/routes.rb
Sharebox::Application.routes.draw do

  resources :folders

  resources :assets

  devise_for :users

    root :to => "home#index"

  match "assets/get/:id" => "assets#get", :as => "download"

end

app/models/asset.rb
class Asset < ActiveRecord::Base

  attr_accessible :user_id, :uploaded_file, :folder_id

  def file_size
    uploaded_file_file_size
  end


  belongs_to :user
  has_attached_file :uploaded_file,
                    :url => "/assets/get/:id",
                    :path => "Rails_root/assets/:id/:basename.:extension"

  validates_attachment_size :uploaded_file, :less_than => 10.megabytes
  validates_attachment_presence :uploaded_file


  def file_name
    uploaded_file_file_name
  end

  def file_size
    uploaded_file_file_size
  end

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree
  attr_accessible :name, :parent_id, :user_id
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_id, :uploaded_file





  validates :email, :presence => true, :uniqueness => true
  has_many :assets
  has_many :folders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!  #authenticate for users before any methods is called

  def index
    @assets = current_user.assets
  end

  def show
    @asset = current_user.assets.find(params[:id])
  end

  def new
    @asset = current_user.assets.new
  end

  def create
    @asset = current_user.assets.build(params[:asset])
    if @asset.save
      redirect_to @asset, :notice => "Successfully updated asset."

    end
  end

  def edit
    @asset = current_user.assets.find(params[:id])
  end

  def update
    @asset = current_user.assets.find(params[:id])
    if @asset.update_attributes(params[:asset])
      redirect_to @asset, :notice  => "Successfully updated asset."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @asset = current_user.assets.find(params[:id])
    @asset.destroy
    redirect_to assets_url, :notice => "Successfully destroyed asset."
  end



  #this action will let the users download the files (after a simple authorization check)
  def get
    asset = current_user.assets.find_by_id(params[:id])
    if asset
      send_file asset.uploaded_file.path, :type => asset.uploaded_file_content_type
    else
      flash[:error] = "Don't be cheeky! Mind your own assets!"
      redirect_to assets_path
    end

  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @folders = current_user.folders
  end

  def show
    @folder = current_user.folders.find(params[:id])
  end

  def new
    @folder = current_user.folders.new
  end

  def create
    @folder = current_user.folders.new(params[:folder])
    if @folder.save
      redirect_to @folder, :notice => "Successfully created folder."
    else
      render :action => 'new'
    end
  end

  def edit
    @folder = current_user.folders.find(params[:id])

  end

  def update
    @folder = current_user.folders.find(params[:id])
    if @folder.update_attributes(params[:folder])
      redirect_to @folder, :notice  => "Successfully updated folder."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @folder = current_user.folders.find(params[:id])
    @folder.destroy
    redirect_to folders_url, :notice => "Successfully destroyed folder."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      @assets = current_user.assets.order("uploaded_file_file_name desc")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/assets/_form.html.erb
<%= form_for @asset, :html => {:multipart => true} do |f| %>
    <%= f.error_messages %>
    <p>
      <%= f.label :uploaded_file, "File" %><br>
      <%= f.file_field :uploaded_file %>
    </p>
    <p><%= f.submit "Upload" %></p>
<% end %>

app/views/assets/edit.html.erb
<% title "Edit Asset" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @asset %> |
  <%= link_to "View All", assets_path %>
</p>

app/views/assets/index.html.erb
<% title "Assets" %>
<table>
  <tr>
    <th>Uploaded Files</th>
  </tr>
  <% for asset in @assets %>
      <tr>
        <td><%= link_to asset.file_name, download_url(asset) %>  </td>
        <td><%= link_to "Show", asset %></td>
        <td><%= link_to "Edit", edit_asset_path(asset) %></td>
        <td><%= link_to "Destroy", asset, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<p><%= link_to "New Asset", new_asset_path %></p>

app/views/assets/new.html.erb
<% title "Upload a file" %>

<%= render 'form' %>

<p><%= link_to "Back to List", root_url %></p>

app/views/assets/show.html.erb
<% title "Asset" %>

<p>
  <strong>User:</strong>
  <%= @asset.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_asset_path(@asset) %> |
  <%= link_to "Destroy", @asset, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", assets_path %>
</p>

app/views/folders/_form.html.erb
<%= form_for @folder do |f| %>
<%= f.error_messages %>
<p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p><%= f.submit "Create Folder" %></p>
<% end %>

app/views/folders/edit.html.erb
<% title "Edit Folder" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @folder %> |
  <%= link_to "View All", folders_path %>
</p>

app/views/folders/index.html.erb
<% title "Folders" %>

<table>
  <tr>
    <th>Name</th>
    <th>Parent</th>
    <th>User</th>
  </tr>
  <% for folder in @folders %>
    <tr>
      <td><%= folder.name %></td>
      <td><%= folder.parent_id %></td>
      <td><%= folder.user_id %></td>
      <td><%= link_to "Show", folder %></td>
      <td><%= link_to "Edit", edit_folder_path(folder) %></td>
      <td><%= link_to "Destroy", folder, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Folder", new_folder_path %></p>

app/views/folders/new.html.erb
<% title "New Folder" %>

<%= render 'form' %>

<p><%= link_to "Back to List", folders_path %></p>

app/views/folders/show.html.erb
<% title "Folder" %>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>
<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @folder.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_folder_path(@folder) %> |
  <%= link_to "Destroy", @folder, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", folders_path %>
</p>

app/views/home/index.html.erb
<% unless user_signed_in? %>
    <h1>Welcome to ShareBox</h1>
    <p>File sharing web application you can't ignore.</p>

<% else %>
    <div id="menu">
      <ul id= "top_menu">
        <li><%= link_to "Upload", new_asset_path %></li>
      </ul>
    </div>

    <div class="asset_list_header">
      <div class="file_name_header">File Name</div>
      <div class="file_size_header">Size</div>
      <div class="file_last_updated_header">Modified</div>
    </div>
    <div class="asset_list">
      <% @assets.each do |asset| %>
          <div class="asset_details">
            <div class="file_name"><%= link_to asset.file_name, download_url(asset) %></div>
            <div class="file_size"><%=number_to_human_size(asset.file_size, :precision => 2)   %></div>
            <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>
          </div>
      <% end %>
    </div>
<% end %>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareBox | <%= content_for?(:title) ? yield(:title) : "File-sharing web app" %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
</head>
<body>
<div id="login_user_status">
  <% if user_signed_in? %>
      <%= current_user.email  %>
      |
      <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
      <em>Not Signed in.</em>
      <%= link_to 'Sign in', new_user_session_path%>
      or
      <%= link_to 'Sign up', new_user_registration_path%>
  <% end %>
</div>
<div class="header_wrapper">
  <div class="logo">
    <%= link_to "ShareBox", root_url %>
  </div>
</div>
<div id="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= content_tag :h1, yield(:title) if show_title? %>
  <%= yield %>
</div>
</body>
</html>